name: continuous integration

on:
  push:
    branches:    
      - master

jobs:
  continuous_integration:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-dotnet@master
      with:
        dotnet-version: '2.2.401'
    - run: dotnet test source\DefaultEcs.Test\DefaultEcs.Test.csproj -c Release
    - run: dotnet tool install -g coverlet.console
    - run: coverlet source\DefaultEcs.Test\bin\Release\netcoreapp2.2\DefaultEcs.Test.dll -t "dotnet" -a "vstest source\DefaultEcs.Test\bin\Release\netcoreapp2.2\DefaultEcs.Test.dll" -o coverage\lcov.info -f lcov
    - uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}