name: continuous integration

on:
  push:
    branches:
      - master
    paths:
      - 'source/DefaultEcs/**'

jobs:
  continuous_integration:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up dotnet
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '5.0.0'
        source-url: https://nuget.pkg.github.com/Doraku/index.json
      env:
        NUGET_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}

    - name: Run tests net452
      run: dotnet test source\DefaultEcs.Test\DefaultEcs.Test.csproj -c Release -f net452

    - name: Run tests net48
      run: dotnet test source\DefaultEcs.Test\DefaultEcs.Test.csproj -c Release -f net48

    - name: Run tests net5.0
      run: dotnet test source\DefaultEcs.Test\DefaultEcs.Test.csproj -c Release -f netcoreapp3.0

    - name: Create package
      run: dotnet pack source\DefaultEcs\DefaultEcs.csproj -c Release -o package -p:PackageReleaseNotes="${{ github.sha }}"

    - name: Publish package
      run: nuget push package\*.nupkg
