name: continuous integration

on:
  push:
    branches:    
      - master

jobs:
  continuous_integration:
    runs-on: windows-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: Set up dotnet
      uses: actions/setup-dotnet@master
      with:
        dotnet-version: '2.2.401'
        
    - name: Set DOTNET_ROOT environment variable
      run: cmd FOR /F "tokens=*" %g IN ('where dotnet') do (SET DOTNET_ROOT=%g)

    - name: Run tests
      run: dotnet test source\DefaultEcs.Test\DefaultEcs.Test.csproj -c Release

    - name: Install coverlet tool
      run: dotnet tool install -g coverlet.console

    - name: Create coverage file
      run: coverlet source\DefaultEcs.Test\bin\Release\netcoreapp2.2\DefaultEcs.Test.dll -t "dotnet" -a "vstest source\DefaultEcs.Test\bin\Release\netcoreapp2.2\DefaultEcs.Test.dll" -o coverage\lcov.info -f lcov

    - name: Upload to coverall
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.github_token }}