name: continuous integration

on:
  push:
    branches:    
      - master

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '2.2.401'
    - run: dotnet test source\DefaultEcs.Test\DefaultEcs.Test.csproj -c Release
    - if: github.ref == 'master'
      run: echo master
